### ISSUE TITLE
Font-Awesome Config Example

### ISSUE THREAD

**Issue by Megachill** [userquin/vuetify-nuxt-module#10]
Please show how to add fontawesome to this.

**Comment by userquin** [comment]
Something like this? I'll try to add support for icons (I use `UnoCSS` preset icons and so I don't need this)

```ts
import { defineNuxtPlugin } from '#app'
// Ensure your project is capable of handling css files
// THIS SHOULD BE ADDED TO THE HEAD import '@fortawesome/fontawesome-free/css/all.css'
import { aliases, fa } from 'vuetify/iconsets/fa'

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.hook('vuetify:configuration', async ({ vuetifyOptions }) => {
    // update vuetifyOptions
   vuetifyOptions.icons: {
      defaultSet: 'fa',
      aliases,
      sets: { fa },
    },
  })
})
```

**Comment by userquin** [comment]
maybe you can also add it to the module configuration, you need to solve the css part

**Comment by userquin** [comment]
Anyway PR welcome

**Comment by userquin** [comment]
I'll try to update the playground to show how to use [UnoCSS Preset Icons](https://unocss.dev/presets/icons).

**Comment by userquin** [comment]
I need to change `src/runtime/vuetify.ts` plugin before publishing `0.2.0`
