### ISSUE TITLE
Default true for includeTransformAssetsUrls

### ISSUE THREAD

**Issue by TechAkayy** [userquin/vuetify-nuxt-module#107]
Just a follow-up on this feature - https://github.com/userquin/vuetify-nuxt-module/issues/81. 

It might be worth setting the default to `true` (currently false), so that alias resolving is automatic. I can't think of any use case where user do not want to have this set automatically.

KaelWD's comment (https://github.com/vuetifyjs/vuetify-loader/issues/237#issuecomment-1277816055) suggest that the original intention was to automatically support it with Vuetify vite plugin, which was not possible at their end, but is possible with our module 👍

**Comment by userquin** [comment]
@TechAkayy it should be easy: https://github.com/userquin/vuetify-nuxt-module/blob/main/src/utils/configure-nuxt.ts#L16

**Comment by TechAkayy** [comment]
I will give it a shot, thanks for the pointer 👍
