### ISSUE TITLE
create vuetify:created hook

### ISSUE THREAD

**Issue by GaborTorma** [userquin/vuetify-nuxt-module#111]
Please extend your hooks with vuetify:created.

await nuxtApp.hooks.callHook('vuetify:created', { vuetify })

Insert into this file, after provide: https://github.com/userquin/vuetify-nuxt-module/blob/15e2d30dea17e0a95311e4193275ea25038fffad/src/runtime/plugins/config.ts#L17

I would like to create nuxt-vuetify3-dialog plugin and I need the vuetify instance for.
https://github.com/ThomasLeconte/vuetify3-dialog

**Comment by userquin** [comment]
closed via #112
