### ISSUE TITLE
[Bug]: can't import clickOutside directive

### ISSUE THREAD

**Issue by mtdvlpr** [userquin/vuetify-nuxt-module#118]
Hi, I'm trying to import the ClickOutside directive, but I'm getting the following error:

```
[plugin:vite:import-analysis] Failed to resolve import "vuetify/directives/C" from "../../../../../@nuxt-vuetify-configuration/vuetify-configuration". Does the file exist?
/@nuxt-vuetify-configuration/vuetify-configuration:1:20
1  |  import { C } from 'vuetify/directives/C'
   |                     ^
2  |  import { l } from 'vuetify/directives/l'
3  |  import { i } from 'vuetify/directives/i'
```

**Comment by userquin** [comment]
@mtdvlpr minimal reproduction please...

**Comment by mtdvlpr** [comment]
> @mtdvlpr minimal reproduction please... (you can open this repo in stackblitz, check link in readme file)
> 
> https://github.com/userquin/vuetify-nuxt-module#-install

https://github.com/mtdvlpr/reproduction

**Comment by userquin** [comment]
@mtdvlpr it seems I'm spliting the directive name instead the array  :sweat_smile: 

Remove the directive until I fix and release a new version.

![Captura de pantalla 2023-10-09 174635](https://github.com/userquin/vuetify-nuxt-module/assets/6311119/02fdf27a-ea10-484e-b5bb-1cdb62a2dca7)

**Comment by userquin** [comment]
@mtdvlpr as workaround configue true, I'm finishing the PR, release in a few minutes...

**Comment by userquin** [comment]
![imagen](https://github.com/userquin/vuetify-nuxt-module/assets/6311119/587f4bed-9a18-43c7-8d38-1a1cfe170116)
