### ISSUE TITLE
Using sass variables breaks transition components

### ISSUE THREAD

**Issue by Mattymoo007** [userquin/vuetify-nuxt-module#133]
**Dependencies:**
"nuxt": "^3.8.0",
"sass": "^1.69.5",
"vuetify-nuxt-module": "^0.6.0"

**Node v18.18.0**

@userquin thanks for the awesome module!

I'm having an issue using Vuetify transition components (eg. `<v-expand-transition>`) in combination with custom sass variables. 

I've made a minimal reproduction here: https://stackblitz.com/edit/broken-v-transition?file=app.vue

Is this a known issue and is there a way to work around it?

Thanks again for all the awesome work!

**Comment by userquin** [comment]
You need to import `vuetify/styles`: check the new plugin in this modified repro https://stackblitz.com/edit/broken-v-transition-7tuv5g?file=app.vue,nuxt.config.ts,plugins%2Fvuetify.client.ts

**Comment by Mattymoo007** [comment]
@userquin Great that seems to solve the issue! 😄 I added `vuetify/styles` to the css in my `nuxt.config.ts`. Thanks again 🙏
