### ISSUE TITLE
Question: How would I set `ssr.clientWidth` on each request with this module?

### ISSUE THREAD

**Issue by ttonyh** [userquin/vuetify-nuxt-module#134]
How would I set `ssr.clientWidth` on each request with this module?

I'm currently doing it now (not currently using this module, but would like to start). This is so that I can detect if they are mobile or not via `User-Agent` to and set a width. I see you implemented SSR hints, which is great but only Chrome based browsers currently supports them.

**Comment by userquin** [comment]
You dont need to check user agent, just enable ssr in nuxt and enable http client hints, you can use vietify composables to check the size (if it is sm, lg...), the module will configure vuetify options properly.

**Comment by userquin** [comment]
Upps, client viewport not yet included... I'm working on a Nuxt PR.

**Comment by userquin** [comment]
The server plugin will request http client hints if missing from client and enabled in the module configuration.
Then the client will request the same page (chromium browser only) sending back the client hints.
Then the serve plugin will configure vuetify ssr options before creating the plugin.
Finally, when your app calls `useDisplay` in the server, vuetify will use ssr options.
I have also this another package to check mobile using User Agent Client Hints in client and server: https://github.com/userquin/detect-browser-es (will be used also in my nuxt pr). I have no idea about vuetify logic to detect mobile, if it based on client viewport I guess it is not a good one (I prefer narrow screen or xs or sm).

The server plugin can be found here https://github.com/userquin/vuetify-nuxt-module/blob/main/src/runtime/plugins/vuetify-client-hints.server.ts
