### ISSUE TITLE
How to use blackguard theme with this module?

### ISSUE THREAD

**Issue by hermesalvesbr** [userquin/vuetify-nuxt-module#138]
First, thank you for your time and dedication to this important module for nuxt. It's helping a lot.

I believe I don't know how to use it, and I didn't find documentation or issue on the case, I set the configuration like this:
```
 vuetify: {
        vuetifyOptions: {
            labComponents: true,
            theme: {
                defaultTheme: 'dark',
            },
        } 
    },
```

However, if I use the 'system' or 'blackguard' theme it returns this error message:
![Captura de tela de 2023-11-05 12-12-13](https://github.com/userquin/vuetify-nuxt-module/assets/379850/a06dc07d-89d6-4f74-ab22-9a868389f04e)

**Comment by userquin** [comment]
Try adding dark theme: https://github.com/userquin/vuetify-nuxt-module/blob/main/playground/vuetify.config.mts#L41

**Comment by hermesalvesbr** [comment]
Dark works fine, the new theme called blackguard didnt work.

**Comment by userquin** [comment]
@hermesalvesbr can you link to the docs for system/blackguard themes?

**Comment by hermesalvesbr** [comment]
I saw the ad:
https://vuetifyjs.com/en/introduction/roadmap/

And I saw inside the code:
https://github.com/vuetifyjs/vuetify/blob/622bfc8f93a93ab732c2a8a9641c0dd08cee43b2/packages/docs/src/components/app/Markup.vue#L204

**Comment by hermesalvesbr** [comment]
Thank you
