### ISSUE TITLE
Failed to resolve component: v-data-table

### ISSUE THREAD

**Issue by cll0ud** [userquin/vuetify-nuxt-module#157]
After updating to a vuetify `3.4.0` compatible version(v0.6.6 or v0.6.7) I keep getting these warnings and my VDataTable components won't render anymore.

I removed the `labComponents` setting from my `vuetify.config.ts` file, otherwise I get the following error:
`Cannot destructure property 'from' of 'importMapLabComponents[component]' as it is undefined.`

Have I missed anything? Is there any new setting that I need to use after this update?

**Comment by userquin** [comment]
@cll0ud You only need to remove new Vuetify components from `labComponents`

**Comment by cll0ud** [comment]
You know what? It was my lockfile that was preventing vuetify from updating to 3.4.0 even tho my IDE was saying it was updated. My bad!
