### ISSUE TITLE
Very inconsistent SASS variable definition

### ISSUE THREAD

**Issue by daniandl** [userquin/vuetify-nuxt-module#159]
Please see https://stackblitz.com/edit/nuxt-starter-kttcxr?file=app.vue for reproduction.

When configuring SASS variables for components, they usually need to be defined inside settings.scss (the one used by configFile). Then to actually load the vuetify theme, you need to make a `main.scss` and `@use vuetify` where you can define **global** variables. 

This is confusing, but this could be fixed with simply documenting it somewhere.
However, it gets even more confusing when a component like [VBtn needs to go look for a variable inside a global variable](https://github.com/vuetifyjs/vuetify/blob/e36974ebe0cd214cc5dff5398054cad2d139abb5/packages/vuetify/src/components/VBtn/_variables.scss#L27). Then we need to define the global variable once inside main.scss and once within settings.scss, as the respective variables are both missing from eachother in these contexts...

Is this a Vuetify issue or something in this module?

PS: I think there may also be a weird caching issue with these 2 SCSS files, as while I was ripping my hair out trying to understand why "variables weren't updating", my page would respond to the variable changes on refresh and then quickly switch back to an old version of the file once hydrating. When looking at the cache headers, it's supposed to use no-cache... Has anyone else had this problem or am I losing my mind :D

**Comment by daniandl** [comment]
Played around a bit more and I think this is just the result of very unfortunate naming style at Vuetify...
When changing `$typography.button` in `main.scss`, it will apply changes to class `text-button`. While changing it in `settings.scss` will apply to all buttons by default...

No idea why it was decided to solve it this way... either way, the caching issue is still there.

**Comment by userquin** [comment]
this module does nothing about styles, just configures the entry properly: check pinned issue #19

**Comment by daniandl** [comment]
Yeah, this is a Vuetify issue, I will close it.
The caching issue is weird though, `settings.scss` does not get cache-busted properly when running dev server.
