### ISSUE TITLE
[Bug] module types conflict with `@vite-pwa/nuxt` module types

### ISSUE THREAD

**Issue by mtdvlpr** [userquin/vuetify-nuxt-module#163]
I'm not sure if this bug is because of `vuetify-nuxt-module` or `@vite-pwa/nuxt`, but depending on the order, the types of `vuetify-nuxt-module` are overwritten by the `@vite-pwa/nuxt` types. [See reproduction](https://github.com/mtdvlpr/reproduction/tree/vuetify).

```javascript
modules: ["vuetify-nuxt-module", "@vite-pwa/nuxt"] // works
modules: ["@vite-pwa/nuxt", "vuetify-nuxt-module"] // error on vuetify config object
```

**Comment by userquin** [comment]
I'll check it in 1 hour or so...

**Comment by userquin** [comment]
@mtdvlpr thx man, I have no idea why is vuetify there!, maybe a copy/paste, my fault, fixing it

**Comment by userquin** [comment]
:cry: 

![imagen](https://github.com/userquin/vuetify-nuxt-module/assets/6311119/1dbc9673-3005-43bb-9765-71ae12328f3f)

**Comment by userquin** [comment]
upps, the issue should be on Nuxt PWA integration

**Comment by userquin** [comment]
closing this since this module seems to be fine, please refer to this other issue https://github.com/vite-pwa/nuxt/issues/98

**Comment by userquin** [comment]
@mtdvlpr using `@vite-pwa/nuxt v0.3.2`

![imagen](https://github.com/userquin/vuetify-nuxt-module/assets/6311119/6b2e55f6-2285-40be-b1fb-3091e9251f14)
