### ISSUE TITLE
Using with Tailwind

### ISSUE THREAD

**Issue by Niki2k1** [userquin/vuetify-nuxt-module#168]
Is there an example how to completely integrate tailwind and remove utility classes?

I have multiple issues when trying to:
1. blueprint is not getting loaded (I am trying to use md3)
2. Hover and active colors are broken (worked before turning off utilities)
![image](https://github.com/userquin/vuetify-nuxt-module/assets/31246997/34997aae-12a6-413c-b6db-0c31efae1980)
3. I have to set important in tailwind because vuetify is always loaded as last.
4. I get 404's when using a `settings.scss`
![image](https://github.com/userquin/vuetify-nuxt-module/assets/31246997/38b569b8-2dfd-4323-9987-b421acdfa9c0)

**Comment by Niki2k1** [comment]
Ok I managed to resolve the error.
Instead of having an `settings.scss`
```scss
@use 'vuetify/settings' with (
  $utilities: false
);
```
 and having it added via the vuetify module options.

 I now just use a `main.scss` with the following content:
```scss
@use "vuetify" with (
  $utilities: false
);
```

**Comment by userquin** [comment]
@Niki2k1 have you test with solution in pinned issue? https://github.com/userquin/vuetify-nuxt-module/issues/115

**Comment by Niki2k1** [comment]
That helped thank you, I searched everything, discord other issues but did not check the pinned issues.... 😅
