### ISSUE TITLE
Sass Variables and duplicate styles

### ISSUE THREAD

**Issue by danilpon98** [userquin/vuetify-nuxt-module#172]
Hi,
After various tests, I noticed that overriding sass variables only works if I import the css 'vuetify/styles' in the 'nuxt.config.ts' file. In the attached example, you can verify this by commenting out the lines:
` css: ['vuetify/styles']` or `css: ['~/assets/styles/main.scss']`

But when I add one of the lines, I get duplicate styles (see screenshot)
![screenshot](https://github.com/userquin/vuetify-nuxt-module/assets/43674808/f80f4505-3fb2-4fcd-8efa-2696ba0fcfac)

Repro - https://stackblitz.com/edit/broken-v-transition-r9fbp1?file=nuxt.config.ts

Tell me what I'm doing wrong. Thanks!

**Comment by userquin** [comment]
Check vuetify docs, there is a warning about it iirc. Check also this pinned issue:
https://github.com/userquin/vuetify-nuxt-module/issues/115
