### ISSUE TITLE
How to work with NuxtIcon

### ISSUE THREAD

**Issue by Henvy-Mango** [userquin/vuetify-nuxt-module#180]
```
  vuetify: {
    vuetifyOptions: {
      icons: {
        defaultSet: 'nuxt-icon',
      }
    },
  },
```
I try this `nuxt.config.ts`, but it seems not to work.
The [guide ](https://vuetify-nuxt-module.netlify.app/guide/icons/svg-icons.html) said can use NuxtIcon SVG icons libraries, but I have no idea how to do that.

**Comment by AasmundN** [comment]
Maybe see issue #93

**Comment by userquin** [comment]
https://github.com/userquin/vuetify-nuxt-icon-integration with SVG and CSS support (not at same time)

**Comment by userquin** [comment]
New entry added to docs: https://vuetify-nuxt-module.netlify.app/guide/icons/integrations.html

If missing page await PWA update the new version

**Comment by Henvy-Mango** [comment]
Thank you! It help me a lot
