### ISSUE TITLE
ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time

### ISSUE THREAD

**Issue by stephenjason89** [userquin/vuetify-nuxt-module#190]
Getting this on latest 0.10.1 ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time

<img width="995" alt="image" src="https://github.com/userquin/vuetify-nuxt-module/assets/3810177/360e2c7d-f831-42ef-8c5b-81f6f324ce0f">

how to reproduce:
pnpm add -D vuetify-nuxt-module

add 		'vuetify-nuxt-module',
to modules

pnpm dev

Please note that everything is working except it is throwing an error

**Comment by userquin** [comment]
duplicated #190

**Comment by MathieuDerelle** [comment]
> duplicated #190

you probably meant #177 :D
