### ISSUE TITLE
Overriding Vuetify style for SSG

### ISSUE THREAD

**Issue by Robin-kwan** [userquin/vuetify-nuxt-module#192]
Hi, I'd like to override Vuetify style with css for static site.
I have everything in main.scss and set it in css in Nuxt.config.
In local, it seems to work fine but when I deployed to static hosting or set SSR to false. The stylesheet ordering in <head> tag is different and overriding no longer work.

Btw, I might consider doing it in Vuetify config but I'd like to use my custom css variables which I'm not sure if it is possible to use them in the config file.

Could anyone please guide me this ?

**Comment by userquin** [comment]
You can hack prerendered pages at build  time (generate) detecting your styles and reverting the order on each html page.

**Comment by Robin-kwan** [comment]
Okay I'll check it out. Thanks for quick response.
