### ISSUE TITLE
Font Awesome Pro giving me imports error

### ISSUE THREAD

**Issue by GreyXor** [userquin/vuetify-nuxt-module#200]
Hello,
I'm following this doc: https://vuetify-nuxt-module.netlify.app/guide/icons/svg-icons.html#font-awesome-pro
I would indeed like to use font awesome pro (I have the license) but I get this error
`[nuxt] #imports should be transformed with real imports. There seems to be something wrong with the imports plugin.
`

It this line, that causing the issue : 
```typescript
              [/* default export? */false, /* export name */ 'fad', /* library */ '@fortawesome/pro-duotone-svg-icons']
```
I'm not sure if i'm doing something wrong or if there's a real issue with `vuetify-nuxt-module`

**Comment by userquin** [comment]
check https://github.com/userquin/vuetify-nuxt-module/issues/44

**Comment by GreyXor** [comment]
> check #44

Thanks but what you want me to check exactly ? It's not really related to my imports issue.

**Comment by userquin** [comment]
do you have included all fa-pro deps?

**Comment by userquin** [comment]
nuxt version?

**Comment by userquin** [comment]
can you provide a minimal private repo here in GitHub and send me an invitation?

**Comment by userquin** [comment]
I've sent you a private DM in discord
