### ISSUE TITLE
Vuetify SASS variables don't work and broke styles

### ISSUE THREAD

**Issue by itelmenko** [userquin/vuetify-nuxt-module#204]
I try to use SASS variables. But it don't work and broke styles. I see black borders for inputs. But I didn't add their. 

`frontend/assets/css/custom/settings.scss`:

```
@use 'vuetify/settings' with (
  $button-height: 50px,
  $messages-font-size: 0.85rem,
  $input-details-font-size: 0.85rem,
  $messages-min-height: 0.9rem,
  $input-details-font-weight: 300,
  $text-field-details-padding-inline: 0px
);

```

In `frontend/nuxt.config.ts`:
```
...
moduleOptions: {
            styles: {
                configFile: 'assets/css/custom/settings.scss',
            },
        },
...
```

![vuetify_black_borders](https://github.com/userquin/vuetify-nuxt-module/assets/495449/0c0f6245-b96c-4efd-89f4-3504caa32e1a)

If I remove moduleOptions's content, black borders go away.

![vuetify_without_variables](https://github.com/userquin/vuetify-nuxt-module/assets/495449/9fd7db78-c74e-446d-91f9-e18d919505cb)

vuetify-nuxt-module  version: "0.12.0"

**Comment by itelmenko** [comment]
Minimal reproduction example - https://github.com/itelmenko/nuxt-vuetify-with-module-example

**Comment by fredimitchel** [comment]
Did you tried with `@forward` instead of `@use` ?

**Comment by itelmenko** [comment]
Yes. https://github.com/itelmenko/nuxt-vuetify-with-module-example/blob/main/assets/css/settings.scss

**Comment by fredimitchel** [comment]
Can you try following ?

```scss
@forward 'vuetify/settings' with (
  $button-height: 50px,
  $messages-font-size: 0.85rem,
  $input-details-font-size: 0.85rem,
  $messages-min-height: 0.9rem,
  $input-details-font-weight: 300,
  $text-field-details-padding-inline: 0px
);
@import 'vuetify';
```

**Comment by itelmenko** [comment]
Hm.... Yes. It works
![image](https://github.com/userquin/vuetify-nuxt-module/assets/495449/7bda2214-6557-41f9-9f7f-8a7f77391a84)

**Comment by fredimitchel** [comment]
It seems that defining a config file is fully overriding the vuetify config

**Comment by fredimitchel** [comment]
@userquin ?

**Comment by userquin** [comment]
Using the reproduction with Chrome 123 just works (after an inital delay: using `@use`  instead `@forward`)

**Comment by itelmenko** [comment]
@userquin My example works fine for you without changes?

With 

```
@forward "vuetify/settings" with (
  $button-height: 50px,
  $messages-font-size: 0.85rem,
  $input-details-font-size: 0.85rem,
  $messages-min-height: 0.9rem,
  $input-details-font-weight: 300,
  $text-field-details-padding-inline: 0px
);
```

Could you attach a screen?

**Comment by userquin** [comment]
With `@use`:

![imagen](https://github.com/userquin/vuetify-nuxt-module/assets/6311119/cc79841f-97df-4608-96ec-5cf8d340c174)

With `@forward`:

![imagen](https://github.com/userquin/vuetify-nuxt-module/assets/6311119/e823cbd3-6da2-4d21-a99d-0de1e58092bf)

**Comment by itelmenko** [comment]
Please add `@import 'vuetify';` also:

```
@forward 'vuetify/settings' with (
  $button-height: 50px,
  $messages-font-size: 0.85rem,
  $input-details-font-size: 0.85rem,
  $messages-min-height: 0.9rem,
  $input-details-font-weight: 300,
  $text-field-details-padding-inline: 0px
);
@import 'vuetify';
```

**Comment by userquin** [comment]
![imagen](https://github.com/userquin/vuetify-nuxt-module/assets/6311119/8aa6662d-039b-44e5-8460-8a15f69fce5a)

**Comment by userquin** [comment]
I'm not a SASS expert, you should try also building the reproduction and run the preview (`node .output/server/index.mjs` or `npx serve .output/public` if using `nuxt build`  or `nuxt generate` respectively): IIRC some styles are in reverse order and maybe you need to patch the output build.

**Comment by santiagoaloi** [comment]
> Yes. I see **Select** was fixed on last screen. So what is correct way?
> 
> ```
> @forward 'vuetify/settings' with (
> ...
> );
> @import 'vuetify';
> ```
> 
> ?

I'm also encountering difficulties with Sass and the  `vuetify-nuxt-module` 🙃

Never do this in your vuetfiy Sass file:

```sass
@import 'vuetify'
```

Becuase it imports all of Vuetify's styles into every component, leading to:

1. Massive CSS Duplication: 
2. Unnecessary styles bloat your CSS bundle, impacting performance.
3. Style Pollution: Global styles might conflict with your component-specific styles.
4. Increased Bundle Size: Larger CSS files take longer to load, slowing down your application.

Surely, there must be a better way to handle this. 
If anyone has discovered a solution or workaround, I'd greatly appreciate your insights and suggestions!

**Comment by santiagoaloi** [comment]
I created an issue about this with a reproduction repo #212

**Comment by santiagoaloi** [comment]
> Yes. I see **Select** was fixed on last screen. So what is correct way?
> 
> ```
> @forward 'vuetify/settings' with (
> ...
> );
> @import 'vuetify';
> ```
> 
> ?

[v0.13.2](https://github.com/userquin/vuetify-nuxt-module/releases/tag/v0.13.2) fixes this issue, so you just need to use as follows, no additional css imports are required.


```js
//nuxt.config.ts
  vuetify: {
    moduleOptions: {
      styles: {
        configFile: 'assets/scss/settings.scss',
      },
    },
  },
 ```
 
 ```scss
 // assets/scss/settings.scss
@forward 'vuetify/settings' with (
  // Buttons
  $button-disabled-opacity: 0.5,
);
```

**Comment by itelmenko** [comment]
Thank you so much! It works excellent!

**Comment by shivamp-argus** [comment]
Hello @santiagoaloi ,
I am trying to override variables defined by vuetify and loading them using my below `nuxt.config,js` file.
I am able to see a moment where I am able to see unstyled components, I want to avoid that. 
Can you kindly share your insights?

```typescript
export default defineNuxtConfig({
  devtools: { enabled: true },

  alias: {
    '@test': resolve(__dirname, 'unitTestUtils'),
    '/src': resolve(__dirname, 'src'),
    '/components': resolve(__dirname, 'src/common/components'),
    '/assets': resolve(__dirname, 'assets'),
    '/plugins': resolve(__dirname, 'plugins')
  },

  rootDir: join(process.cwd(), rootDirFrontend),
  mode: 'spa',

  server: {
    host: '0.0.0.0'
  },

  app: {
    head: {
      titleTemplate: '%s',
      meta: [
        {
          name: 'viewport',
          content: 'width=device-width, initial-scale=1'
        }
      ],
      style: [
        {
          cssText: '#nuxt-loading { display: none !important; }',
          type: 'text/css'
        }
      ],
      // Material Symbols (Icons).
      link: [
        {
          rel: 'stylesheet',
          href: 'https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,400,0..1,0'
        }
      ]
    }
  },

  vite: {
    plugins: [
      ViteYaml(),
      vuetify({
        autoImport: true,
        styles: {
          configFile: 'src/styles/settings.scss'
        }
      })
    ],
    vue: {
      template: {
        transformAssetUrls
      }
    }
  },

  vue: {
    runtimeCompiler: true
  },

  loading: {
    color: '#68BFEC',
    failedColor: '#d84b37',
    height: '5px'
  },

  spaLoadingTemplate: join(process.cwd(), './page-loader.tpl.html'),

  router: {
    scrollBehavior: function () {
      return { x: 0, y: 0 };
    }
  },

  ssr: false,

  build: {
    transpile: ['vuetify']
  },

  pages: true,
  compatibilityDate: '2025-06-12'
});
```
