### ISSUE TITLE
Discrepancy in documentation and mdi icon set

### ISSUE THREAD

**Issue by trc-mathieu** [userquin/vuetify-nuxt-module#214]
Hi, it is mentioned in the documentation https://github.com/userquin/vuetify-nuxt-module/blob/e402bf8118616e335061dbc59f8a85a9d9d92fa0/docs/guide/index.md?plain=1#L279 that the default mdi icon used is loaded from CDN and will use the @latest. But in fact, it's using the @5.x version. https://github.com/userquin/vuetify-nuxt-module/blob/e402bf8118616e335061dbc59f8a85a9d9d92fa0/src/utils/icons.ts#L36

Would it be possible to change it so that it uses latest instead?
Thanks!

**Comment by userquin** [comment]
Check https://vuetifyjs.com/en/features/icon-fonts/#mdi-css (using icons.ts link).

You can change the cdn entry to use latest version, check https://vuetify-nuxt-module.netlify.app/guide/icons/font-icons.html.

I need to update the types.ts module and the md file in the docs, mdi icon font link in the page using 5.x

**Comment by trc-mathieu** [comment]
Thanks for the quick response!

**Comment by trc-mathieu** [comment]
@userquin 
So I tried but it doesn't work.  The  generated file `vuetify-icons-configuration` contains twice the mdi import. Looks like the sets are not merged.
```
import {aliases,mdi} from "/_nuxt/node_modules/.pnpm/vuetify@3.5.7_typescript@5.4.5_vite-plugin-vuetify@2.0.3_vue@3.4.23/node_modules/vuetify/lib/iconsets/mdi.mjs?v=5640749c"
import {aliases,mdi} from "/_nuxt/node_modules/.pnpm/vuetify@3.5.7_typescript@5.4.5_vite-plugin-vuetify@2.0.3_vue@3.4.23/node_modules/vuetify/lib/iconsets/mdi.mjs?v=5640749c"
export const enabled = true
export const isDev = true
export function iconsConfiguration() {

  return {
    defaultSet: 'mdi',
    aliases,
    sets: { mdi,mdi }
  }
}
```

**Comment by userquin** [comment]
@trc-mathieu I cannot reproduce it, it is working in the playground in the repo...

**Comment by userquin** [comment]
check if you have the mdi icon set added twice in the config file

**Comment by trc-mathieu** [comment]
I'm using it from a layer, might be something related to this. I'll investigate more...
