### ISSUE TITLE
Configuring icon set in layer end up with duplicated imports

### ISSUE THREAD

**Issue by guibulator** [userquin/vuetify-nuxt-module#217]
Hi, it relates to this issue that was just closed: https://github.com/userquin/vuetify-nuxt-module/issues/214

I created a reproduction: https://github.com/guibulator/vuetify-nuxt-issue-repro/tree/main

**Comment by userquin** [comment]
@guibulator should be fixed in `v0.13.3`

**Comment by guibulator** [comment]
works fine, thank you for your quick actions on this!
