### ISSUE TITLE
Cannot override theme when theme is defined in base layer

### ISSUE THREAD

**Issue by guibulator** [userquin/vuetify-nuxt-module#218]
Hi, this might also be related to the way you deal with layers but I found another issue. Related to https://github.com/userquin/vuetify-nuxt-module/issues/217
In my base layer, I define the primary color as red. In the application config file, I should be able to override the color of the base layer.

I created a reproduction here: https://github.com/guibulator/vuetify-nuxt-issue-repro/tree/extending-theme

**Comment by userquin** [comment]
@guibulator should be fixed in `v0.13.3`

**Comment by guibulator** [comment]
@works fine, thank you for your quick actions on this!
