### ISSUE TITLE
v-img images broken on nuxi dev mode

### ISSUE THREAD

**Issue by sk8killer** [userquin/vuetify-nuxt-module#220]
In dev mode ssr = false. In prod mode ssr = true.
This works (in dev and prod mode) : 
`<img
          src="~/assets/img/fond.jpg"
        >`

this works in prod mode but DOES NOT WORK in dev mode : 
`<v-img
          src="~/assets/img/fond.jpg"
        >`

The includeTransformAssetsUrls option is set to true in both modes.

I've been pulling my hair out for 1 hour. Please help !

**Comment by userquin** [comment]
@sk8killer Vuetify and Nuxt versions?

**Comment by sk8killer** [comment]
I found the mistake, sorry about that.

I forgot to include this line in nuxt.config.ts :

`vite: { 
vue: {
      template: {
        transformAssetUrls
      }
    }
}`

this works now. Thank you for this wonderfull package !

**Comment by userquin** [comment]
you shouldn't need to include that entry, it is enabled by default in the vuetify nuxt module: it will add that entry for you

**Comment by userquin** [comment]
no, should install latest version, can you check instaleld vuetify and vuetify vite plugin versions?

**Comment by userquin** [comment]
The `transformAssetUrls` comes with the vuetify vite plugin

**Comment by sk8killer** [comment]
these packages are installed :
- vuetify 3.5.15
- vite-plugin-vuetify 2.0.3

**Comment by userquin** [comment]
that's weird, should be fine, I'm going to prepare a reproduction, I cannot reproduce it in the playground here...

**Comment by userquin** [comment]
https://stackblitz.com/edit/github-2nc5a9?file=package.json,app.vue,nuxt.config.ts

**Comment by userquin** [comment]
it seems a problem with vue or nuxt version, now `nuxt.options.vite.vue.template.transformAssetUrls` is not undefined, I'm going to merge them.

**Comment by userquin** [comment]
@sk8killer linked reproduction working on my local using linked PR, requested a review from Daniel, maybe I can release it tmr, in the meantime use your workaround, once released it should work without it.

**Comment by userquin** [comment]
@sk8killer can you try with `v0.13.4`?

**Comment by amari10-2** [comment]
@userquin 
hi.
sorry for asking closed issue, but i just in the same situation.

config
ssr = false

first tried with latest version.
- nuxt 3.12.3
- vuetify 3.6.11
- vuetify-nuxt-module 0.14.1
- vite-plugin-vuetify 2.0.3

using v-img, src used path of '/assets/xxx/yyy.png' starting with '@' or '~'. but not change to '/_nuxt/' and not viewable.
(when used img tag viewable)

second tried with fix version of this issue
- nuxt 3.11.2
- vuetify 3.6.11
- vuetify-nuxt-module 0.13.4
- vite-plugin-vuetify 2.0.3

but same result as latest version.

confirmed viewable version
- nuxt 3.11.1
- vuetify 3.6.11
- vuetify-nuxt-module 0.13.2
- vite-plugin-vuetify 2.0.3

in this configuration, viewable assets.

**Comment by userquin** [comment]
Open a new issue 🙏 , I need to review latest changes in nuxt 3.12.* and fix the layers problem

**Comment by amari10-2** [comment]
#237 
opend issue
