### ISSUE TITLE
Parsing error when using a vuetify locale

### ISSUE THREAD

**Issue by eiggiotti** [userquin/vuetify-nuxt-module#222]
Hi!

I've encountered a bug while trying to use the vuetify french locale with this config:
```typescript
import { fr } from 'vuetify/locale';

export default defineNuxtConfig({
  devtools: { enabled: false },
  modules: ['vuetify-nuxt-module'],
  vuetify: {
    vuetifyOptions: {
      locale: {
        locale: 'fr',
        messages: { fr },
      },
    },
  },
});
```

The console gives this error:
```
 ERROR  Pre-transform error: Failed to parse source for import analysis because the content contains invalid JS syntax. If you are using JSX, make sure to name the file with the .jsx or .tsx extension.
```
And the page displays this error:
![image](https://github.com/userquin/vuetify-nuxt-module/assets/5744574/5d8c35c7-8a68-4e39-89c3-99ffdbcae8ac)

I've created [this stackblitz](https://stackblitz.com/edit/nuxt-starter-5eidjr?file=nuxt.config.ts) to see the bug for yourself.

The problem seems to come from [this code](https://github.com/userquin/vuetify-nuxt-module/blob/main/src/vite/vuetify-configuration-plugin.ts#L52):
```typescript
        return `${result.imports}

export const isDev = ${ctx.isDev}
export function vuetifyConfiguration() {
  const options = JSON.parse('${JSON.stringify(newVuetifyOptions)}')
  ${result.directives}
  ${result.aliases}
  ${result.components}
  ${result.messages}
  return options
}
${deepCopy
  ? `function deepCopy(src,des) {
    for (const key in src) {
      if (typeof src[key] === 'object') {
        if (typeof des[key] !== 'object') des[key] = {}
        deepCopy(src[key], des[key])
      } else {
        des[key] = src[key]
      }
    }
  }
  `
  : ''
}
`
```
When `newVuetifyOptions` contains a single quote character, as it is the case when using the [french locale](https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/locale/fr.ts#L12), the generated code is no longer valid.

**Comment by userquin** [comment]
@eiggiotti I'm fixing the configuration when providing `locale.messages` (in the meantime, if you are using only `fr` entries you can remove messages entry and the import and use `localeMessages` instead):

```ts
    vuetifyOptions: {
      locale: {
        locale: 'fr',
      },
      localeMessages: ['fr'],
    },
```

**Comment by eiggiotti** [comment]
Thank you @userquin, that fixes it!
