### ISSUE TITLE
Update Vuetify

### ISSUE THREAD

**Issue by kleuschner** [userquin/vuetify-nuxt-module#224]
How can I update vuetify without the version dependency from this module?

For example:
vuetify-nuxt-module ships vuetify 3.5.2 as dependency, but there is vuetify 3.5.4 and I want to update to this version, but still want to use vuetify-nuxt-module.
Can I do this?

**Comment by userquin** [comment]
Just add vuetify dependency to your project, you can also use:
- `resolutions` for yarn and pnpm
- `overrides` for npm

**Comment by kleuschner** [comment]
Thanks.

I've tried it, but i'm getting runtime vuetify errors.
Even if I use 3.5.14 in "overrides" or as dependency. And also if I install exactly the same version (3.5.13) it's breaking.

Could you upgrade the vuetify dependency to 3.6.x please?
