### ISSUE TITLE
How to use mdi-svg

### ISSUE THREAD

**Issue by BobTheShoplifter** [userquin/vuetify-nuxt-module#225]
In vue 2 the trick was: 

```js
import { mdiArrowDownRight, mdiFormatQuoteOpen, mdiArrowRight } from '@mdi/js'
```

then 

```vue
<v-icon size="19" :icon="mdiArrowRight"></v-icon></v-avatar>
```

But does it auto import the icons when setting

```js
defaultSet: 'mdi-svg',
```

How can i for example use mdiArrowRight in my page?

**Comment by userquin** [comment]
https://vuetify-nuxt-module.netlify.app/guide/icons/integrations.html

**Comment by userquin** [comment]
If the question is about using it with `v-icon` you should ask in `vuetify` repo.

**Comment by BobTheShoplifter** [comment]
Importing works but i was wondering how the mdi-svg worked

**Comment by userquin** [comment]
Check any repo here: https://vuetify-nuxt-module.netlify.app/guide/icons/integrations.html

Basically `v-icon` accepts an string or a component, it just renders it: `@mdi/js`  just exports the svg icons as js objects, then `v-icon` just renders the corresponding icon.

**Comment by BobTheShoplifter** [comment]
Yeah, i am wondering how do i access the js object that @mdi/js exports?

**Comment by userquin** [comment]
just import the icon you want

**Comment by BobTheShoplifter** [comment]
Aha! Yes this is what i am doing right now. I just tought the imports was automatic in all components and pages
