### ISSUE TITLE
Directives can be used without registering

### ISSUE THREAD

**Issue by kingyue737** [userquin/vuetify-nuxt-module#226]
### Actual behavior
I didn't register `v-tooltip` but I could still use it:
![image](https://github.com/userquin/vuetify-nuxt-module/assets/40021217/b276719d-b2c5-44bc-a122-07ca877b8afd)

### Expected behavior
According to the docs, the users are required to set 
```ts
export default defineNuxtConfig({
  modules: ['vuetify-nuxt-module'],
  vuetify: {
    vuetifyOptions: {
      directives: 'Tooltip' // or true
    }
  }
})
```

### Reproduction
https://stackblitz.com/edit/github-fi3r47-mf4yjn

**Comment by userquin** [comment]
The `v-tooltip` directive is a wrapper around `VTooltip` component, and so, when using it the `VBtn` will try to resolve `VTooltip` component.
