### ISSUE TITLE
Uncaught SyntaxError: Identifier 'VDatePicker' has already been declared

### ISSUE THREAD

**Issue by lna1989** [userquin/vuetify-nuxt-module#228]
If you make an alias on a VDatePicker, there will be a declaration error in the console.

Example: https://stackblitz.com/edit/nuxt-starter-pqlhoy?file=vuetify.config.ts

Steps for playback:
1.Follow the link from [example](https://stackblitz.com/edit/nuxt-starter-pqlhoy?file=vuetify.config.ts)
2. Open the developer console and see the error

Additional information: At the same time, it is impossible to interact with the application, as well as with the displayed calendars on the main page.

**Comment by userquin** [comment]
Working SB reproduction: https://stackblitz.com/edit/nuxt-starter-ng15sv?file=package.json
