### ISSUE TITLE
Cookie color-scheme does not work when using npx nuxi generate

### ISSUE THREAD

**Issue by ForexPro117** [userquin/vuetify-nuxt-module#230]
During use I change the theme with
`const toggleTheme = () => (theme.global.name.value = theme.global.name.value == 'light' ? 'dark' : 'light')`
In development mode this creates a cookie and after reboot the theme changes, but in static mode this does not happen

**Comment by userquin** [comment]
The cookie will work only with SSR app, generate command will use SSR only to build the app (SSG). You need to update the logic to your build process, the vuetify module cannot do anything about this.

With client only app, why do you need a cookie? use local storage or browser preferences.
