### ISSUE TITLE
Hydration style mismatch on <VMain />

### ISSUE THREAD

**Issue by Endermanch** [userquin/vuetify-nuxt-module#232]
### This should be fixed ASAP
The most basic functionality of providing the layout for the application is broken.

![image](https://github.com/userquin/vuetify-nuxt-module/assets/44542704/000b1cdf-bc69-48dd-9591-f0cd5407b97d)

**Reproduction:**
```vue
<VApp full-height theme="light">
  <VLocaleProvider locale="ru">
    <VLayout>
      <NuxtLoadingIndicator />
      <NuxtLayout>
        <Header /> <!-- vappbar + vnavigationdrawer -->
        <VMain>
          <NuxtPage />
        </VMain>
        <LazyFooter app /> <!-- vfooter -->
      </NuxtLayout>
    </VLayout>
  </VLocaleProvider>
</VApp>
```

**Temporary resolution:**
Just hardcode the styles. This will break if any of the layout elements have dynamic width/height.
```vue
<VMain
  style="
    --v-layout-left: 0px;
    --v-layout-right: 0px;
    --v-layout-top: 110px;
    --v-layout-bottom: 300px;
  "
>
```

**Comment by userquin** [comment]
Try moving the content to `layouts/default.vue`: check https://github.com/userquin/nuxt-vuetify-issue-205-v-issue-19015/tree/nuxt-vuetify-issue-232 (there is a PR with the changes).

It seems Vuetify with some problem related to https://github.com/userquin/vuetify-nuxt-module/issues/205#issuecomment-2241086187 (when enabling ssr client hints we get missmatch warning about z-index, when disabling ssr client hints the missmatch warning about left position)
