### ISSUE TITLE
mdi-Icons with Custom-SVG-Icons

### ISSUE THREAD

**Issue by julschne** [userquin/vuetify-nuxt-module#234]
Hi there,

I'm currently using mdi-icons as the default icon set, which works great. However, I now need to incorporate custom SVG icons stored in the assets/icons folder. To achieve this, I've installed the nuxt-icons module since it supports custom icons.

My goal is to consistently use the `<v-icon>` tag for all icons, for example:
```html
<v-icon>mdi-aws</v-icon>
```
and
```html
<v-icon>my-custom-svg-icon</v-icon>
```

How can I configure this setup?

**Comment by userquin** [comment]
check https://github.com/userquin/vuetify-nuxt-icon-integration (https://vuetify-nuxt-module.netlify.app/guide/icons/integrations.html)
