### ISSUE TITLE
Please add compatibility matrix in readme.md

### ISSUE THREAD

**Issue by DevDengChao** [userquin/vuetify-nuxt-module#235]
Everytime I want to add Vuetify to a Nuxt project, I have to check both @nuxtjs/vuetify and vuetify-nuxt-module to see if one of them is compatible with my project. 

But there is no simple indicators nor introductions which Vuetify and Nuxt is supported, so I have to check the package.json mannually.

Please try add one, thanks.

Example:
+ https://docs.gradle.org/current/userguide/compatibility.html
+ https://kotlinlang.org/docs/multiplatform-compatibility-guide.html

**Comment by userquin** [comment]
This module should be compatible with any Nuxt 3.6.5+ and Vuetify 3.*, rn I only need to include support for 3.12.*.

I'll try to add a custom page to the docs...

**Comment by DevDengChao** [comment]
Good to hear that .

**Comment by userquin** [comment]
@DevDengChao I do my best with older versions checking tags and commits, I'll keep the new page updated for new releases.
