### ISSUE TITLE
vuetifyImportPlugin ignores excluded components/directives from vuetifyModule option

### ISSUE THREAD

**Issue by AndreyYolkin** [userquin/vuetify-nuxt-module#236]
Similar to https://github.com/userquin/vuetify-nuxt-module/issues/226, but with further investigation

## Version

`vuetify: 3.6.11`
`nuxt-vuetify-module: 0.14.1`
`nuxt: 3.12.3`

## Intro

We have VuetifyOptions with directives and components fields

```ts
 { /**
   * @default false
   */
  directives?: Directives,

  /**
   * @default false
   */
  components?: Components
}
```

However, selected options does't make an effect on vite-plugin, as it still autoimports the components and directives

The reason is https://github.com/userquin/vuetify-nuxt-module/blob/be68923fa4a46c45bf2ade1f0070319b84ceb608/src/utils/configure-vite.ts#L68 is always an empty object

## Case

Part of page:
![image](https://github.com/userquin/vuetify-nuxt-module/assets/11289484/68e0e86f-3aca-44c9-a491-4d1d49edce63)

Default output:
<img width="787" alt="image" src="https://github.com/userquin/vuetify-nuxt-module/assets/11289484/5b10d87f-2c89-4390-b8e4-8ab1443dd64d">

When I pass `{ autoImport: { ignore: ['Tooltip'] }` as argument (+ extra log for options):
<img width="578" alt="image" src="https://github.com/userquin/vuetify-nuxt-module/assets/11289484/fa355062-b1b2-471e-882e-e53b3e2d1a21">

I expect that options provided in directives and components will effect on autoImports list

**Comment by userquin** [comment]
I'll keep current behavior, the linked PR no makes sense, check https://github.com/userquin/vuetify-nuxt-module/pull/239#issuecomment-2223534574

**Comment by userquin** [comment]
I'm going to update the docs... auto import is better than changing the configuration or deal with errors.

**Comment by AndreyYolkin** [comment]
I still doubt, because if I register directive via nuxtApp.vueApp.directive() with VTooltipName it will be overrided. Probably we  can address the issue to the vuetify vite plugin itself, but as a compromise i would suggest adding another option inside moduleConfig to fine-tune the vite plugin

**Comment by userquin** [comment]
Why? If you use some directive/component, the plugin will auto import them for you, that's the expected behavior.

Why do you need to register the directive if the plugin will do it for you? We're using Vite (Rollup), no dead code and no code duplication.

**Comment by AndreyYolkin** [comment]
I don't want to use the tooltip provided by vuetify, but want to have own directive with the same name (v-tooltip is very common). The only way for now is to write custom autoimport rule to resolve cutom directive before it's done by vuetify

**Comment by userquin** [comment]
@AndreyYolkin that's another problem, cannot use `x-tooltip` for example

**Comment by userquin** [comment]
I'll try to add ignore directives option, the option will be provided directly to the vuetify plugin
