### ISSUE TITLE
can't using '@' or '~' in v-img

### ISSUE THREAD

**Issue by amari10-2** [userquin/vuetify-nuxt-module#237]
can't using '@' or '~' in v-img. but viewable by img tag.

config
ssr = false

first tried with latest version.

- nuxt 3.12.3
- vuetify 3.6.11
- vuetify-nuxt-module 0.14.1
- vite-plugin-vuetify 2.0.3

using v-img, src used path of '/assets/xxx/yyy.png' starting with '@' or '~'. but not change to '/_nuxt/' and not viewable.

second tried version

- nuxt 3.11.2
- vuetify 3.6.11
- vuetify-nuxt-module 0.13.4
- vite-plugin-vuetify 2.0.3

but same result as latest version.

confirmed viewable version

- nuxt 3.11.1
- vuetify 3.6.11
- vuetify-nuxt-module 0.13.2
- vite-plugin-vuetify 2.0.3

viewable in this configuration by v-img with '@' or '~'.

help!

**Comment by userquin** [comment]
Small change in Nuxt `3.11.2`, I'm preparing a PR for Nuxt `3.11.2+` support

**Comment by userquin** [comment]
@amari10-2 can you check with `v0.15.0`? You should include latest vue version and dedupe dependencies (remove `node_modules` and install dependencies or if you're using `pnpm`  run  ``pnpm dedupe`)

**Comment by amari10-2** [comment]
@userquin 
sorry I'm late.

i created a new plain project on StackBlitz.
(i just added vuetify-nuxt-module to the nuxt starter.)

however, when I use v-img, '@' and '~' are not converted.

do i need to configure anything?

https://stackblitz.com/edit/nuxt-starter-m7ccj9?file=app.vue

**Comment by userquin** [comment]
I think you are using public resources wrongly: `public` folder shouldn't be used with any alias/resolver other than the default provided by Vite or Nuxt (via base prefix):
- https://vitejs.dev/guide/assets.html#the-public-directory
- https://nuxt.com/docs/guide/directory-structure/public

No idea why Nuxt resolving the favicon in `img`, may be broken when building...

Anyway, the `includeTransformAssetsUrls` not being initialized properly, by default it should be enabled but missing in the default module options.
