### ISSUE TITLE
floating-vue does not work

### ISSUE THREAD

**Issue by sdr0x07b6** [userquin/vuetify-nuxt-module#249]
I installed a library called `floating-vue` and it did not work.
Upon further investigation, I found that it would not work if `vuetify-nuxt-module` was installed.

I have asked in the `floating-vue` side Issue, but no answer so far.
https://github.com/Akryum/floating-vue/issues/1046

In it, I have Stackblitz to reproduce the problem.
https://stackblitz.com/edit/nuxt-starter-ldfg7v?file=package.json,nuxt.config.ts,app.vue

In environments where `vuetify-nuxt-module` is installed, certain slots (`#popper`) seem to be disabled, is there any information or possible cause for this?

**Comment by userquin** [comment]
There is a collision with floating vue global components and vuetify ones.

You can import floating vue components and use them or write a custom nuxt plugin and/or module to register them with other names. The floating vue nuxt module will register the floating vue plugin (also css and some vite options) and the components.

For example, changing the app.vue to this just works:
<details>
<summary><i>app.vue</i></summary>

Floating vue seems to be not working when enabling SSR, the popup id will change and them hydration missmatch there.

```html
<script setup lang="ts">
import { Tooltip as FTooltip, Menu as FMenu, Dropdown as FDropdown } from 'floating-vue'
</script>

<template>
  <div>
    <NuxtRouteAnnouncer />

    <FDropdown id="one" :distance="6">
      <button>Click me</button>
      <template #popper> ... </template>
    </FDropdown>

    <FTooltip id="two">
      <a>Sponsor me</a>
      <template #popper> ... </template>
    </FTooltip>

    <FMenu id="three">
      <button>Documentation</button>
      <template #popper> ... </template>
    </FMenu>
  </div>
</template>
```
</details>

![imagen](https://github.com/user-attachments/assets/13bc4b3f-0bf5-4c8f-ac1a-2cab0c4042c3)

**Comment by sdr0x07b6** [comment]
I see, now that you mention it there is a name collision. I wonder why I didn't notice that 🫠
It worked! Thank you for explaining it so carefully!
