### ISSUE TITLE
Bump Vuetify to v3.6.14

### ISSUE THREAD

**Issue by shawn-mty** [userquin/vuetify-nuxt-module#250]
There is a RuntimeModuleHooks warning whenever you do a build in vuetify-nuxt-module. This is due to Vuetify having a slightly old version with an old version of sass.

Here is what it looks like:
![image](https://github.com/user-attachments/assets/76f4d54e-3425-4128-981b-b70d0808b11c)

This is fixed in Vuetify v3.6.14

Shall I jump on this?

Thanks

**Comment by userquin** [comment]
The warning can be ignored, using old nuxt build module, it generates the old interface, I will try to update it: the warning not related to vuetify, it is a nuxt warning.

About vuetify version. You can add it to your dependencies, I only release a new version when there is a new vuetify minor (next will be for vuetify 3.7).

**Comment by userquin** [comment]
Maybe you can try with vite 5.4.0 and new sass options: install vite 5.4.0 as dev dependency and add this inside `vite` option in nuxt cobfig file: https://github.com/vuetifyjs/vuetify/pull/20260/files#diff-be942263511e50feadc9ad6b917071e137c2cdb7d981c683f3b1bf5cd6501388R55

**Comment by shawn-mty** [comment]
> Maybe you can try with vite 5.4.0 and new sass options: install vite 5.4.0 as dev dependency and add this inside `vite` option in nuxt config file: https://github.com/vuetifyjs/vuetify/pull/20260/files#diff-be942263511e50feadc9ad6b917071e137c2cdb7d981c683f3b1bf5cd6501388R55
> 

Thank you sir!

I'll try it out
