### ISSUE TITLE
add support for theme configuration

### ISSUE THREAD

**Issue by leo91000** [userquin/vuetify-nuxt-module#43]
After reading the file `/src/vite/vuetify-configuration-plugin.ts` I didn't see some kind of support for theme configuration at plugin level.

Is it something that is doable ?

Is there a better opiniated way to do it (e.g `useTheme()`) ?

Thanks !

**Comment by userquin** [comment]
@leo91000 add the theme to vuetifyOptions in the module or add a nuxt plugin adding `vuetify:configuration` hook.

**Comment by userquin** [comment]
@leo91000 what's the issue?
