### ISSUE TITLE
Working with font-awesome pro ?

### ISSUE THREAD

**Issue by GreyXor** [userquin/vuetify-nuxt-module#44]
Hello, I have a Font-Awesome Pro license and this is my package.json
```
  "devDependencies": {
    "@fortawesome/fontawesome-svg-core": "^6.4.0",
    "@fortawesome/pro-duotone-svg-icons": "^6.4.0",
    "@fortawesome/vue-fontawesome": "^3.0.3",
    "nuxt": "^3.6.3",
    "vuetify-nuxt-module": "^0.4.4"
  }
```

But I get this message : 
```
 WARN  Missing library @fortawesome/free-solid-svg-icons dependency, install it!                                                                                                                           nuxt:vuetify 9:46:46 AM

 WARN  No icons found, icons disabled! 
```

Do I miss something ? I don't need `free-solid-svg-icons`, just the `pro-duotone`, thanks!

**Comment by userquin** [comment]
@GreyXor can you shared the configuration to add the fa pro library?
You only need to add the library in `fa.svg.libraries` option https://vuetify-nuxt-module.netlify.app/guide/icons/svg-icons.html#fa-svg

**Comment by userquin** [comment]
If you dont specify any library, the module will add the free library...

**Comment by GreyXor** [comment]
```ts
   vuetify: {
    vuetifyOptions: {
      icons: {
        defaultSet: 'fa-svg',
        svg: {
          fa: {
            libraries: [
              [false, 'fa','@fortawesome/pro-duotone-svg-icons']
            ]
          }
        }
      }
    }
  }
```

I got this error 
```
[nuxt] [request error] [unhandled] [500] Cannot read properties of undefined (reading 'prefix')                                                                                                                        11:53:54 AM
  at _pullDefinitions (./node_modules/.pnpm/@fortawesome+fontawesome-svg-core@6.4.0/node_modules/@fortawesome/fontawesome-svg-core/index.mjs:1155:35)  
  at Array.reduce (<anonymous>)  
  at Library.add (./node_modules/.pnpm/@fortawesome+fontawesome-svg-core@6.4.0/node_modules/@fortawesome/fontawesome-svg-core/index.mjs:1137:35)  
  at Module.iconsConfiguration (/@nuxt-vuetify-configuration/vuetify-icons-configuration:16:33)  
  at Module.configureIcons (./node_modules/.pnpm/vuetify-nuxt-module@0.4.4_@nuxt+kit@3.6.3_vite-plugin-vuetify@1.0.2_vuetify@3.3.8/node_modules/vuetify-nuxt-module/dist/runtime/plugins/icons.mjs:4:48)  
  at ./node_modules/.pnpm/vuetify-nuxt-module@0.4.4_@nuxt+kit@3.6.3_vite-plugin-vuetify@1.0.2_vuetify@3.3.8/node_modules/vuetify-nuxt-module/dist/runtime/plugins/vuetify-icons.mjs:7:27  
  at ./node_modules/.pnpm/nuxt@3.6.3_@types+node@20.4.2_rollup@2.79.1/node_modules/nuxt/dist/app/nuxt.js:63:44  
  at fn (./node_modules/.pnpm/nuxt@3.6.3_@types+node@20.4.2_rollup@2.79.1/node_modules/nuxt/dist/app/nuxt.js:156:44)  
  at Object.callAsync (./node_modules/.pnpm/unctx@2.3.1/node_modules/unctx/dist/index.mjs:68:55)  
  at ./node_modules/.pnpm/nuxt@3.6.3_@types+node@20.4.2_rollup@2.79.1/node_modules/nuxt/dist/app/nuxt.js:158:56
```
![image](https://github.com/userquin/vuetify-nuxt-module/assets/79602273/8f0aa73f-bc45-4d4e-9907-a20bff01fe1b)

**Comment by userquin** [comment]
@GreyXor how do you install it in a normal project?

**Comment by userquin** [comment]
you can check it in dev tools:

![imagen](https://github.com/userquin/vuetify-nuxt-module/assets/6311119/390b8fd7-6696-4861-af3e-f506b070fdda)

**Comment by GreyXor** [comment]
Now it's working with this configuration : 
```
  vuetify: {
    vuetifyOptions: {
      icons: {
        defaultSet: 'fa-svg',
        svg: {
          fa: {
            libraries: [
              [false, 'fad','@fortawesome/pro-duotone-svg-icons']
            ]
          }
        }
      }
    }
  },
```
But not the animation, like
```
<v-icon>fa-duotone fa-server</v-icon> // is working
<v-icon>fa-duotone fa-server fa-bounce</v-icon> // isn't
```

**Comment by userquin** [comment]
uhmm, maybe we also need the css? try adding the fa pro css in the nuxt config file inside css.

**Comment by GreyXor** [comment]
I don't think so because it working with
`  <font-awesome-icon icon="fad fa-server" spin />`

**Comment by userquin** [comment]
how do you install it via `createVuetify`?

**Comment by GreyXor** [comment]
I haven't used createVuetify but https://github.com/userquin/vuetify-nuxt-module/issues/44#issuecomment-1637042349

**Comment by userquin** [comment]
try adding bounce/spin to the `v-icon`

**Comment by GreyXor** [comment]
```
  <font-awesome-icon icon="fad fa-server" bounce />
  <v-icon>fa-duotone fa-server fa-bounce</v-icon>
  <v-icon>fa-duotone fa-server</v-icon>
```
Give me (the first one is animated correctly)
![image](https://github.com/userquin/vuetify-nuxt-module/assets/79602273/8adb906c-e8fd-496c-adff-1dc543df0382)

**Comment by userquin** [comment]
Try with this:
`<v-icon bounce>fa-duotone fa-server</v-icon>`
`<v-icon class="bounce">fa-duotone fa-server</v-icon>`
`<v-icon class="fa-bounce">fa-duotone fa-server</v-icon>`

If it is not working use `font-awesome-icon` instead `v-icon`, maybe Vuetify needs some update.

Can you try it with a Vite Vue project registering fa-prod?

**Comment by GreyXor** [comment]
Thanks,
this one is working
```
 <v-icon class="fa-bounce">fa-duotone fa-server</v-icon>
```

But now, sometimes I'd like to use icons somewhere other than in a `v-icon`.
Example : `<i class="fa-duotone fa-language"></i> Language`
should give 
![image](https://github.com/userquin/vuetify-nuxt-module/assets/79602273/6fd8514b-93e8-4dd1-b070-8cd9d28211f9)

For example, how can I use it with `<i></i>` ?

**Comment by userquin** [comment]
I guess you can't, if you've the svg files in the fa-prod library, you can try [UnoCSS Preset Icons](https://unocss.dev/presets/icons) via [FileSystemIconLoader](https://unocss.dev/presets/icons#node-js)

**Comment by userquin** [comment]
@GreyXor I'm adding font awesome pro configuration and UnoCSS Preset Icons to the docs, including an example in the playground (using mdi and custom svg icons: and maybe replacing mdi icons in Vuetify via pure css svg icons)

**Comment by GreyXor** [comment]
Thank you very much for reactivity !

**Comment by userquin** [comment]
You can use UnoCSS Preset Icons also with `<div class="i-mdi:account"></div>`:
![imagen](https://github.com/userquin/vuetify-nuxt-module/assets/6311119/e31a4338-49c3-417f-bccc-1f81725c79e6)

**Comment by userquin** [comment]
I'll include also `unocss-mdi` as new icon set...
