### ISSUE TITLE
Configuration via a ./vuetify.config.ts file

### ISSUE THREAD

**Issue by tidan-16** [userquin/vuetify-nuxt-module#46]
### Describe the solution you'd like

I would like to be able to add a vuetify.config.js file at the root directory (./vuetify.config.js)

### Additional context

Being able to add the config at the root (vuetify.config.js) would make the nuxt.config.js file cleaner and smaller. Since we all know that the config for vuetify can be almost 50+ lines, it would be nice to seperate it. I know that nuxt i18n allow that and im pretty sure that would be a good approach for this module too. 

Here is the doc for the vue i18n module for that feature:
[https://v8.i18n.nuxtjs.org/options/vue-i18n](https://v8.i18n.nuxtjs.org/options/vue-i18n)

What do you guys think about this idea?

**Comment by userquin** [comment]
Lgtm

**Comment by mubaidr** [comment]
Well you can just define config in `vuetify.config.js` and import `vuetify` options from this file. 

tip: You can use `VOptions` type from this module to ensure typing support.

**Comment by userquin** [comment]
since this can be done with a simple import I'm closing it as not planned

**Comment by mubaidr** [comment]
> since this can be done with a simple import I'm closing it as not planned

But this does not seem to support hot reload. Maybe there should be dedicated readme section how to configure hot reload when using import from file.

**Comment by tidan-16** [comment]
You did it finally? Nice!

**Comment by userquin** [comment]
@tidan-16 yeah, I need to do some more tests... there is a bug in Nuxt/Vite about invalidating virtual modules, check last comment in the PR: https://github.com/userquin/vuetify-nuxt-module/pull/61#issuecomment-1646637032

**Comment by userquin** [comment]
You can heck it in SB: https://stackblitz.com/edit/nuxt-starter-gd81vx?file=vuetify.config.ts

**Comment by tidan-16** [comment]
🐐
