### ISSUE TITLE
Vuetify global components type are any

### ISSUE THREAD

**Issue by pierresaid** [userquin/vuetify-nuxt-module#51]
Repro : 
```shell
npx nuxi@latest init my-app
npm i vuetify-nuxt-module -D 
# add 'vuetify-nuxt-module' to nuxt modules
```
The type of any vuetify global components are `any` in the template.
![image](https://github.com/userquin/vuetify-nuxt-module/assets/32095218/0c35b003-65b1-4346-a538-c0430aa8e1cb)

in `components.d.ts` in GlobalComponents when we change 
`'VBtn': typeof import("../node_modules/vuetify/lib/components/VBtn/index")['VBtn']`
to
`'VBtn': typeof import("../node_modules/vuetify/lib/components/VBtn/index.d.mts")['VBtn']`
or to `'VBtn': typeof import("vuetify/components")['VBtn']`

The typing becomes correct on the template :
![image](https://github.com/userquin/vuetify-nuxt-module/assets/32095218/ebf2532f-2037-409e-b037-7eda60b1d3a9)

I tested this with npm and pnpm in wsl node 19.8.1 and on windows with node 18.12.1 both with vscode typescript and volar takeover mode.

If someone can reproduce this to confirm.

**Comment by userquin** [comment]
@pierresaid can you try with `0.4.10`?

Tests with the playground after running `nr dev:prepare`:

Auto import:
![imagen](https://github.com/userquin/vuetify-nuxt-module/assets/6311119/822f9621-ce21-466e-ae5e-54c8e79f5be5)

VDialog is global:
![imagen](https://github.com/userquin/vuetify-nuxt-module/assets/6311119/849b7c54-dff9-43e6-8ba9-95396a1a66e6)

**Comment by pierresaid** [comment]
It works awesome thanks !
