### ISSUE TITLE
No treeshaking functionality

### ISSUE THREAD

**Issue by Talla2XLC** [userquin/vuetify-nuxt-module#70]
Client load all Vuetify components including JS and styles even if I don't use them in my project:
https://github.com/vuetifyjs/vuetify-loader/assets/50024798/03fae70a-e684-454b-8b3b-b3c6b1e4d18e

my nuxt.config for vuetify:
```
  vuetify: {
    moduleOptions: {
      styles: { configFile: "assets/styles/vuetify-vars.scss" }
    },
    vuetifyOptions: "./config/vuetify.config.ts"
  }
```

**Comment by userquin** [comment]
Can you check it building your app? I need to review it in dev.

**Comment by Talla2XLC** [comment]
> Can you check it building your app? I need to review it in dev.

Not sure what you want me to do but I see styles and js loading for all Vuetify components during my app building (link to screenshot in my first post)

**Comment by userquin** [comment]
Found the problem, it seems I need to transform `vuetify/components` to use the custom component entries, last change I did in `prepare:types` Nuxt hook breaks auto import

**Comment by userquin** [comment]
I'm working on it...
