### ISSUE TITLE
Feature Request - Support for transformAssetUrls

### ISSUE THREAD

**Issue by TechAkayy** [userquin/vuetify-nuxt-module#81]
Currently, we have to manually add transformAssetUrls by importing it from `vite-plugin-vuetify`. 

The default values use `src` while it will be different for nuxt. 

Would be great to have this integrated into our module. Thanks! 

More details here 
- https://github.com/vuetifyjs/vuetify-loader/tree/master/packages/vite-plugin#image-loading (https://github.com/vuetifyjs/vuetify-loader/blob/master/packages/shared/src/index.ts#L52)
- https://stackoverflow.com/a/75511457 (extract below for quick look)
- https://github.com/vuetifyjs/vuetify-loader/issues/237

```
Vuetify's vite plugin has a preset for this to support vuetify components:

// vite.config.js
import vuetify, { transformAssetUrls } from 'vite-plugin-vuetify'

export default {
  plugins: [
    vue({ 
      template: { transformAssetUrls }
    }),
    vuetify(),
  ],
}
```

**Comment by userquin** [comment]
so, you only need a flag to allow add the `transformAssetsUrls`?
