### ISSUE TITLE
[Feature] Add support for google font integration

### ISSUE THREAD

**Issue by mubaidr** [userquin/vuetify-nuxt-module#86]
Vuetify by default google `roboto` font. Would it be a good idea to setup roboto font within this module?

**Comment by mubaidr** [comment]
Material spec stattytes usage of roboto font, so does vuetify 2 here: https://v15.vuetifyjs.com/en/framework/typography/

I don't know why vuetify does not have any reference about this font. But if I load roboto font, it gets applied to application.

**Comment by userquin** [comment]
https://github.com/vuetifyjs/vuetify/blob/fda0d8309d81a7e1a24afffb5167569750e357ab/packages/vuetify/src/styles/settings/_variables.scss#L9

**Comment by userquin** [comment]
There are a few libraries we can use via Nuxt module:
- [UnoCSS Web Fonts Preset](https://unocss.dev/presets/web-fonts)
- [unplugin-fonts](https://github.com/cssninjaStudio/unplugin-fonts)

I'll add both to the docs.

**Comment by userquin** [comment]
I'll close it once added to the docs

**Comment by mubaidr** [comment]
Awesome! Thanks

**Comment by b01010110** [comment]
I've faced this problem recently.
Using 'unplugin-fonts' is a possible way of solving this problem, but I want to suggest another solution without installing any plugins.

Just use a css import style (into your main css file) which google fonts service provides as one of the preferred ways:

_assets/scss/main.scss_
`@import url('https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,300;0,400;0,500;0,700;1,300;1,400;1,500;1,700&display=swap');`

and adjust it into nuxt.config.ts
```
export default defineNuxtConfig({
  css: ['@/assets/scss/main.scss'],
})
```

Don't forget to install sass module. (In this case)
`npm i -D sass`
