### ISSUE TITLE
Little confusion when testing playground - $utilities: false

### ISSUE THREAD

**Issue by TechAkayy** [userquin/vuetify-nuxt-module#91]
I wanted to test turning off $utilities in our playground. Please refer to these four arrows in this screenshot. 
<img width="1349" alt="image" src="https://github.com/userquin/vuetify-nuxt-module/assets/73772701/4a6a5507-4ba1-4855-9a66-8b0f8cd7f122">

1. Clone our module, then `pnpm install`

2. Uncomment the two lines in `playground/nuxt.config.mts` as indicated by the arrows in the left, in order to use `main.scss` & `settings.scss` for sass customization.

3. Start dev-server `pnpm dev`. 

4. `$utilities: false` works (sample page loses design as expected) only when setting it in `main.scss` under `@use "vuetity"`. 

5. `$utilities: false` doesn't have any effect when setting it in `settings.scss` under `@use "vuetify/settings"`, which is contrary to Vuetify docs. 

![image](https://github.com/userquin/vuetify-nuxt-module/assets/73772701/2ed0aca8-656a-4256-bb48-8d3e78da7027)

Wondering if Vuetify docs is wrong, and our playground seem to have `$utilities: false` in both files, and adds to the confusion, and doesn't work as per [Vuetify docs](https://vuetifyjs.com/en/features/sass-variables/#disabling-utility-classes) (or) the [Vuetify vite plugin](https://github.com/vuetifyjs/vuetify-loader/tree/master/packages/vite-plugin#style-loading) readme page. 

Appreciate some clarification here, as official scaffolding using `pnpm create vuetify` doesn't prompt and create a new project fit for sass customization. 

Neither they have any simple sample repos demonstrating how sass customization can be done. This playground is the only place that has a sass setup for the community (as far as I know). 

Thanks!

**Comment by userquin** [comment]
@TechAkayy closing this since we cannot do anything here about this problem, ask in Vuetify Discord server
