### ISSUE TITLE
Add custom icon font

### ISSUE THREAD

**Issue by AasmundN** [userquin/vuetify-nuxt-module#93]
I would like to add a Phosphor icons to my project, and I am trying to include it as a custom icon set like described in the [Vuetify documentation](https://vuetifyjs.com/en/features/icon-fonts/#creating-a-custom-icon-set). However it looks like this module doesn't accept custom icon sets:

```ts
interface IconsOptions {
    /**
     * @default 'mdi'
     */
    defaultSet: IconSetName;
    /**
     * The prefix for UnoCSS Preset Icons.
     *
     * @default 'i-'
     */
    unocssIconPrefix?: string;
    sets?: IconFontName | IconFontName[] | FontIconSet[];
    svg?: {
        mdi?: JSSVGIconSet;
        fa?: FontAwesomeSvgIconSet;
    };
}
```

If I look at the types from Vuetify I can see that `sets` should accept a component

```ts
interface IconSet {
    component: IconComponent;
}
type IconOptions = {
    defaultSet?: string;
    aliases?: Partial<IconAliases>;
    sets?: Record<string, IconSet>;
};
```

which corresponds well with the Vuetify docs for adding a custom icon sets using a render function.

**Comment by userquin** [comment]
@AasmundN can you provide a minimal repro (with plain Vuetify + Vite)? how do you consume the icons? I mean, Phosphor icons are fonts, JS (like mdijs), or can be consumed via SVG?

**Comment by userquin** [comment]
Have you tried using UnoCSS Preset Icons with Iconify Phosphor icon set?

https://icon-sets.iconify.design/ph/

**Comment by AasmundN** [comment]
I was thinking something along the line of this https://stackblitz.com/edit/vue3-vite-starter-fucq1w?file=src%2Fmain.js,src%2FApp.vue,src%2Fstyle.css. Can't get it to work though.

**Comment by userquin** [comment]
@AasmundN sorry, I was finishing some PR in another repos: here a working example via UnoCSS Preset Icons, the unocss-mdi icon set and using Phosphor icons in vuetify components

**Comment by userquin** [comment]
@AasmundN repo updated, plugin simplified: 
```ts
import PhosphorIcons from '@phosphor-icons/vue';
import { aliases, phosphor } from '../phosphor';

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.hook('vuetify:before-create', ({ vuetifyOptions }) => {
    vuetifyOptions.icons = {
      defaultSet: 'phosphor',
      aliases,
      sets: { phosphor },
    };
  });
  nuxtApp.hook('vuetify:ready', () => {
    nuxtApp.vueApp.use(PhosphorIcons);
  });
});
```

**Comment by Q16solver** [comment]
@userquin Is it possible to use any custom vue svg icon component and alias it to vuetify so it can use it as `<v-icon>some icon</v-icon>` I can't see any option to do it in the config, so I assume it's also done by nuxt plugin and hooking into vuetify:before-create?

**Comment by userquin** [comment]
@Q16solver unfortunately there is no support, it is complex to provide a solution that works with any icon provider, use custom and include the logic you need in the plugin hook

**Comment by userquin** [comment]
Here another example using `Iconify Vue Icon`: https://stackblitz.com/edit/nuxt-starter-akbfxa

**Comment by Q16solver** [comment]
I guess that makes sense, the best way I've found is

```ts
import Icon from "@/assets/icons/Icon.vue";
import { toKebabCase } from "@/util/text";

const ComponentMap: Record<string, Component> = {
  Icon,
};

export const IconComponentMap = Object.entries(ComponentMap).reduce<Record<string, Component>>(
  (acc, [name, component]) => {
    acc[toKebabCase(name).toLowerCase()] = component;
    return acc;
  },
  {},
);

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.hook("vuetify:before-create", ({ vuetifyOptions }) => {
    vuetifyOptions.icons = {
      sets: {
        custom: {
          component: (props) => h(props.tag, [h(IconComponentMap[props.icon as string], { class: "v-icon__svg" })]),
        },
      },
    };
  });
});
```

@userquin So I guess there's no way to expose the sets option for custom icon components in the config ts file. The other enquiry I had was regarding if it was possible to just only import SVGs as in the above example I have to make the svg a vue template for whatever reason and h(...) render the component

**Comment by userquin** [comment]
@Q16solver have you tried [unplugin-icons](https://github.com/unplugin/unplugin-icons/) or [NuxtIcon](https://github.com/nuxt-modules/icon)? I suggest you to use [Unocss Preset Icons](https://unocss.dev/presets/icons) (svg icons to your css, if you only need the icon).

With `unplugin-icons`  and `UnoCSS Preset Icons`  you can use custom SVG files also from file system (no idea about `Nuxt Icon`): both using iconify icons (150000+ icons), check https://icones.js.org/

**Comment by AasmundN** [comment]
@userquin Thanks for the example, I will check it out in a couple days. For now I just used `@phosphor-icons/vue` components in the Vuetify slots manually.

**Comment by danilpon98** [comment]
> Here another example using [Iconify Vue Icon](https://iconify.design/docs/icon-components/vue/): https://stackblitz.com/edit/nuxt-starter-akbfxa
@userquin thanks for the example provided. But icons don't work in UI components, for example in VRadio. Help me find a solution

**Comment by userquin** [comment]
The playground here has an example using custom icon for v-checkbox, maybe v-radio icons cannot be changed, check vuetify issues or ask in vuetify discord server.

Provide a small repro , maybe I can check it in a few hours.

**Comment by danilpon98** [comment]
> The playground here has an example using custom icon for v-checkbox, maybe v-radio icons cannot be changed, check vuetify issues or ask in vuetify discord server.
> 
> Provide a small repro , maybe I can check it in a few hours.

I took your reproduction as a basis. https://stackblitz.com/edit/nuxt-starter-pdzvsr?file=app.vue,iconify%2Findex.ts
In the sources of the "VRadio" component, I saw that the "VIcon" component is used, an icon named "$radioOn" is passed in the parameters. I added this name to the aliases list, but it still doesn't work.

Even console.log does not return icon parameters that are declared inside ui components

**Comment by userquin** [comment]
@danilpon98 iconify-icon alieases are wring, we should use dash instead colon (`mdi-` instead `mdi:`), I have changed a some icons here:
https://stackblitz.com/edit/nuxt-starter-al4k5x

**Comment by danilpon98** [comment]
> @danilpon98 iconify-icon aliases are wrong, we should use dash instead colon (`mdi-` instead `mdi:`), I have changed some icons here: https://stackblitz.com/edit/nuxt-starter-al4k5x

@userquin thanks))

**Comment by userquin** [comment]
New entry added to docs: https://vuetify-nuxt-module.netlify.app/guide/icons/integrations.html

If missing page await PWA update the new version.

Added NuxtIcon and unplugin-icons/nuxt entries and examples.
