### ISSUE TITLE
<v-spacer> is no longer in effect after build

### ISSUE THREAD

**Issue by sdr0x07b6** [userquin/vuetify-nuxt-module#96]
Is the following problem caused by `vuetify-nuxt-module`?
I am building a website using Nuxt3.7.1 && vuetify-nuxt-module 0.5.7.
I am using `<v-spacer>` in several places, but when I `yarn build`, the problem is that the `<v-spacer>` does not allocate any space.

When working with `yarn dev`, `<v-spacer>` is converted to `<div class="v-spacer">` and `.v-spacer` has `flex-grow: 1` to reserve space.
However, when built, `<v-spacer>` is converted to `<div class="v-spacer">` but no longer has `flex-grow: 1`, so no space is allocated.

It is `VGrid.css` that gives `.v-spacer` `flex-grow: 1`.
If you try and build with `v-row` or `v-col` somewhere, which are also from the `VGrid` family, the `<v-spacer>` problem goes away.

Perhaps if I don't use `v-row` or `v-col`, the `VGrid` is tree shaken and no longer affects the `.v-spacer`.
Is it possible to use only `<v-spacer>`?

Is this problem related to `vuetify-nuxt-module`?

**Comment by userquin** [comment]
I have no idea, but seems a problem with vuetify styles. Maybe you can add the style if you are not using VGrid.

**Comment by sdr0x07b6** [comment]
Sorry my English is not good enough.
To put it simply, even if use `<v-spacer>`, `VGrid.css` is not bundled when build.

If try using `<v-row>` or `<v-col>`, `VGrid.css` will be bundled and the effect of `<v-spacer>` will take effect.
When only `<v-spacer>` is used, `VGrid.css` is not bundled.

As you say, `<v-spacer>` will work if I add `.v-space { flex-grid: 1 }` myself.
However, I don't think Vuetify is inherently meant to be used while doing that.
And even if I have patched the CSS for `.v-space`, there may be other elements that still need to be patched. I don't think it is something to be used with anxiety.

**Comment by userquin** [comment]
@sdr0x07b6 closesing this since we cannot do anything here about this problem, file an issue in Vuetify repo or ask in Vuetify Discord server
